Add kubeconfig server management tasks (#16)

diff --git a/.github/workflows/molecule.yml b/.github/workflows/molecule.yml
--- a/.github/workflows/molecule.yml
+++ b/.github/workflows/molecule.yml
@@ -7,15 +7,37 @@ on:
       - master
 
 jobs:
+  version:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Check if galaxy.yml has been modified
+        run: |
+          # Get a list of all modified files in this PR
+          FILES_CHANGED=$(git diff --name-only HEAD^ HEAD)
+          echo "Files changed: $FILES_CHANGED"
+
+          # Check if galaxy.yml is in the list of changed files
+          if [[ $FILES_CHANGED != *"galaxy.yml"* ]]; then
+            echo "Error: galaxy.yml has not been modified."
+            exit 1
+          fi
+
   molecule:
     name: molecule
     runs-on: libvirt
+    needs: version
     strategy:
       matrix:
         scenario:
           - install
           - k8s
           - update
+          - api
         image:
           - https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
         include:
